TESTS			 = test_stream test_stream1 test_sorted_runs test_push_sort test_asynchronous_nodes test_asynchronous_stream_sort test_asynchronous_distribute_gather test_materialize
TESTS_NON_MSVC		 = test_asynchronous_stream_sort.as test_asynchronous_stream_sort.as-ba

LIB_SRC			 =
